In [1]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist

In [2]:
df = pd.read_csv('breed_attributes.csv',index_col='Unnamed: 0')

In [3]:
df

Adaptability   All Around Friendliness  \
affenpinscher                               3                         3   
afghan-hound                                4                         4   
american-staffordshire-terrier              2                         4   
australian-terrier                          3                         3   
basenji                                     4                         5   
beagle                                      3                         5   
bedlington-terrier                          4                         5   
bernese-mountain-dog                        2                         5   
black-and-tan-coonhound                     3                         5   
bloodhound                                  3                         5   
border-collie                               3                         4   
border-terrier                              3                         4   
borzoi                                      4                         4   
bouvier-des-flandres                        3                         4   
boxer                                       3                         4   
briard                                      3                         4   
chesapeake-bay-retriever                    3                         3   
chihuahua                                   3                         4   
cocker-spaniel                              4                         4   
collie                                      4                         5   
curly-coated-retriever                      3                         4   
english-foxhound                            3                         4   
english-setter                              3                         5   
flat-coated-retriever                       3                         5   
french-bulldog                              3                         4   
giant-schnauzer                             2                         3   
golden-retriever                            3                         5   
gordon-setter                               3                         3   
great-dane                                  2                         5   
great-pyrenees                              3                         4   
...                                       ...                       ...   
doberman-pinscher                           3                         3   
english-cocker-spaniel                      4                         5   
english-springer-spaniel                    3                         5   
entlebucher-mountain-dog                    3                         4   
german-shepherd-dog                         3                         4   
leonberger                                  2                         4   
lhasa-apso                                  4                         3   
maltese-shih-tzu                            3                         3   
pembroke-welsh-corgi                        4                         4   
petit-basset-griffon-vendeen                3                         5   
pocket-beagle                               3                         5   
puggle                                      4                         5   
redbone-coonhound                           3                         4   
cavalier-king-charles-spaniel               4                         5   
boston-terrier                              4                         5   
brussels-griffon                            3                         3   
brittany                                    3                         5   
bullmastiff                                 3                         4   
german-shorthaired-pointer                  2                         4   
belgian-sheepdog                            4                         5   
japanese-chin                               3                         3   
maltese                                     3             

In [4]:
df.iloc[0,:].values

array([3, 3, 4, 2, 3, 5, 5, 1, 4, 1, 3, 2, 4, 3, 3, 4, 4, 1, 4, 3, 4, 4,
       3, 3, 3, 1, 2, 1, 3, 3, 2])

In [5]:
X = df.loc[['american-staffordshire-terrier','miniature-schnauzer','rottweiler'],:]
X

Adaptability   All Around Friendliness  \
american-staffordshire-terrier              2                         4   
miniature-schnauzer                         4                         4   
rottweiler                                  2                         4   

                                 Exercise Needs   Health Grooming  \
american-staffordshire-terrier                4                 3   
miniature-schnauzer                           4                 2   
rottweiler                                    4                 4   

                                 Trainability  \
american-staffordshire-terrier              4   
miniature-schnauzer                         4   
rottweiler                                  4   

                                Adapts Well to Apartment Living  \
american-staffordshire-terrier                                2   
miniature-schnauzer                                           4   
rottweiler                                                    2   

                                Affectionate with Family  Amount Of Shedding  \
american-staffordshire-terrier                         4                   2   
miniature-schnauzer                                    5                   2   
rottweiler                                             5                   4   

                                Dog Friendly  Drooling Potential  \
american-staffordshire-terrier             2                   3   
miniature-schnauzer                        3                   1   
rottweiler                                 2                   4   

                                        ...           \
american-staffordshire-terrier          ...            
miniature-schnauzer                     ...            
rottweiler                              ...            

                                Potential For Playfulness  \
american-staffordshire-terrier                          4   
miniature-schnauzer                                     4   
rottweiler                                              5   

                                Potential For Weight Gain  Prey Drive  \
american-staffordshire-terrier                          2           3   
miniature-schnauzer                                     4           4   
rottweiler                                              5           4   

                                Sensitivity Level  Size  \
american-staffordshire-terrier                  3     3   
miniature-schnauzer                             4     2   
rottweiler                                      4     3   

                                Tendency To Bark Or Howl  \
american-staffordshire-terrier                         4   
miniature-schnauzer                                    3   
rottweiler                                             4   

                                Tolerates Being Alone  Tolerates Cold Weather  \
american-staffordshire-terrier                      2                       2   
miniature-schnauzer                                 5                       4   
rottweiler                                          1                       2   

                                Tolerates Hot Weather  Wanderlust Potential  
american-staffordshire-terrier                      3                     3  
miniature-schnauzer                                 4                     3  
rottweiler                                          3                     2  

[3 rows x 31 columns]

In [6]:
Y = df.loc[['yorkshire-terrier'],:]
Y

Adaptability   All Around Friendliness   Exercise Needs  \
yorkshire-terrier              3                         3                5   

                    Health Grooming   Trainability  \
yorkshire-terrier                 2              3   

                   Adapts Well to Apartment Living  Affectionate with Family  \
yorkshire-terrier                                5                         4   

                   Amount Of Shedding  Dog Friendly  Drooling Potential  \
yorkshire-terrier                   2             3                   1   

                           ...           Potential For Playfulness  \
yorkshire-terrier          ...                                   5   

                   Potential For Weight Gain  Prey Drive  Sensitivity Level  \
yorkshire-terrier                          2           2                  5   

                   Size  Tendency To Bark Or Howl  Tolerates Being Alone  \
yorkshire-terrier     1                         3                      2   

                   Tolerates Cold Weather  Tolerates Hot Weather  \
yorkshire-terrier                       2                      2   

                   Wanderlust Potential  
yorkshire-terrier                     3  

[1 rows x 31 columns]

In [7]:
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics import pairwise_distances_argmin_min, pairwise_distances_argmin
euclidean_distances(X.values,Y.values)

array([[8.36660027],
       [6.78232998],
       [9.89949494]])

In [8]:
np.argmin(euclidean_distances(X,Y))

1

In [9]:
X.iloc[np.argmin(euclidean_distances(X,Y)),:].name

'miniature-schnauzer'

In [20]:
yorkshire = euclidean_distances(df.values,Y.values)

In [38]:
euc_ind = np.argsort(yorkshire.flatten())
euc_ind

array([ 76,  97,   0, 106,  70,  61,  42, 112, 115,  90,  65, 120,  74,
        66,  44,  43, 118,  67,  51,  15,  59,  18, 105,  87,  52,  98,
        49,  13,  38,  14,  33,   3,  83,  24,  48, 111,  46,  47, 104,
        17, 117,  63,  36,  73,  85,  86,  99,  37,  79,  10,  27, 103,
        25,   2,  92,   6,  81,  31,  11,  19,   1,  62,  75,  53, 114,
        84, 100, 101,  94,  77,  93, 116,  34,  57,  39,  21, 110, 119,
        64,  20,  23,  54,  78, 113,  58, 102,  91,  40,  71,  80,   5,
        16, 107,  95, 109,  50,  12,  55,  30,  22,   9, 108,  26,  60,
        72,  32,  89,  68,  96,  69,  28,  29,  41,  35,  56,   8,   4,
        82,  88,  45,   7])

In [42]:
[df.iloc[ind,:].name for ind in euc_ind][1:6]

['lhasa-apso',
 'affenpinscher',
 'brussels-griffon',
 'tibetan-terrier',
 'sealyham-terrier']

In [27]:
df.iloc[76,:].name

'yorkshire-terrier'

In [12]:
len(Y.columns)

31

In [13]:
Y.columns

Index([' Adaptability', ' All Around Friendliness', ' Exercise Needs',
       ' Health Grooming', ' Trainability', 'Adapts Well to Apartment Living',
       'Affectionate with Family', 'Amount Of Shedding', 'Dog Friendly',
       'Drooling Potential', 'Easy To Groom', 'Easy To Train', 'Energy Level',
       'Exercise Needs', 'Friendly Toward Strangers', 'General Health',
       'Good For Novice Owners', 'Incredibly Kid Friendly Dogs',
       'Intelligence', 'Intensity', 'Potential For Mouthiness',
       'Potential For Playfulness', 'Potential For Weight Gain', 'Prey Drive',
       'Sensitivity Level', 'Size', 'Tendency To Bark Or Howl',
       'Tolerates Being Alone', 'Tolerates Cold Weather',
       'Tolerates Hot Weather', 'Wanderlust Potential'],
      dtype='object')

Survey:
    
Adapts Well to Apartment Living: House or apartment?  House = 1 ; Apartment = 5
Good For Novice Owners: Experience Training Dogs? Little: 5 Some: 3 Lots: 1
Sensitivity Level: Hectic Life, young kids, low patience: Yes: 1 No: 5
Tolerates Being Alone: How much time do you spend away from home? Little: 1 Some: 3 Lots: 5
Tolerates Cold Weather: Live in a cold climate?: Yes: 5 No: 1
Tolerates Hot Weather: Live in a hot climate?: Yes: 5 No: 1
Affectionate with Family
Incredibly Kid Friendly Dogs
Have Children? 
Have other dogs?
Active
